// Package audit defines the core Popup entity generated by business rules.
package audit

import (
	"errors"
	"strings"
	"time"
)

// Domain errors for popup validation.
var (
	ErrEmptyPopupEmployee = errors.New("popup employee id cannot be empty")
	ErrEmptyPopupRule     = errors.New("popup rule id cannot be empty")
	ErrEmptyPopupTS       = errors.New("popup timestamp cannot be empty")
	ErrEmptyPopupTitle    = errors.New("popup title cannot be empty")
)

// Popup represents a triggered popup record.
type Popup struct {
	Employee string
	Rule     string
	TS       string
	Title    string
	Body     string
}

// NewPopup creates and validates an immutable Popup entity.
func NewPopup(employee, rule, ts, title, body string) (Popup, error) {
	if strings.TrimSpace(employee) == "" {
		return Popup{}, ErrEmptyPopupEmployee
	}
	if strings.TrimSpace(rule) == "" {
		return Popup{}, ErrEmptyPopupRule
	}
	if strings.TrimSpace(ts) == "" {
		return Popup{}, ErrEmptyPopupTS
	}
	if strings.TrimSpace(title) == "" {
		return Popup{}, ErrEmptyPopupTitle
	}

	return Popup{
		Employee: employee,
		Rule:     rule,
		TS:       ts,
		Title:    title,
		Body:     body,
	}, nil
}

// NewPopupWithTime creates a Popup using a time.Time instance formatted to ISO 8601 (RFC 3339 nano).
func NewPopupWithTime(employee, rule string, ts time.Time, title, body string) (Popup, error) {
	return NewPopup(employee, rule, ts.Format(time.RFC3339Nano), title, body)
}
