// Package audit defines the core Popup entity and query filters generated by business rules.
package audit

// Filter defines search criteria for querying stored popups.
type Filter struct {
	Employee string
	Rule     string
}

// Matches checks whether a given Popup satisfies the filter criteria.
func (f Filter) Matches(p Popup) bool {
	if f.Employee != "" && p.Employee != f.Employee {
		return false
	}
	if f.Rule != "" && p.Rule != f.Rule {
		return false
	}
	return true
}
